  deploy-web-staging:
runs-on: ubuntu-latest
steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup .npmrc and use node 14.15.1
    uses: actions/setup-node@v1
    with:
      node-version: 14.15.1

  - name: Expo Web
    uses: expo/expo-github-action@v5
    with:
      expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
      expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      expo-cache: true

  - name: Install dependencies
    if: steps.yarn-cache.outputs.cache-hit != 'true'
    run: yarn

  - name: Build Expo Web
    working-directory: ./packages/app
    run: expo build:web

  - name: Vercel Deploy
    uses: amondnet/vercel-action@v20.0.0
    with:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      vercel-org-id: vQUYEiDSxr9LHexowynQJcWS
      vercel-project-id: prj_iA4jK514KW6cIIerBJCB4MGFB2PC
      scope: TEAM
